<?php
/**
 * @file
 * Code for the Opengizra material feature.
 */

include_once 'opengizra_material.features.inc';

/**
 * Implements hook_field_attach_form().
 */
function opengizra_material_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  if ($entity_type != 'field_collection_item') {
    return;
  }

  list(,, $bundle) = entity_extract_ids($entity_type, $entity);
  if ($bundle != 'field_source_info') {
    return;
  }

  // Fetch all mass unit types.
  $vocabulary = taxonomy_vocabulary_machine_name_load('measurement_units');
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'taxonomy_term')
    ->fieldCondition('field_unit_type', 'value', 'mass')
    ->propertyCondition('vid', $vocabulary->vid)
    ->execute();

  if (!$result) {
    return;
  }

  // Check if we are in a node context, or directly inside a field
  // collection.
  $key = !empty($form_state['node']) ? 'field_source_info[und][0][field_unit][und]' : 'field_unit[und]';
  $mass_inputs = array();
  foreach (array_keys($result['taxonomy_term']) as $tid) {
    $mass_inputs[] = array(':input[name="' . $key . '"]' => array('value' => $tid));
  }
  $state = array(
    '#states' => array(
      'visible' => array($mass_inputs),
    ),
  );

  $form['field_length'] += $state;
  $form['field_length_unit'] += $state;

  $form['field_length']['#element_validate'][] = 'opengizra_material_length_validate';
  $form['field_length_unit']['#element_validate'][] = 'opengizra_material_length_validate';
}

/**
 * Element validate; Make length and unit-length required.
 *
 * If the selected unit is of weighttype (e.g. Kilogram), we need to make
 * those fields required.
 */
function opengizra_material_length_validate($element, &$form_state) {
  return;
  $values = !empty($form_state['values']['field_source_info']) ? $form_state['values']['field_source_info'][LANGUAGE_NONE][0] : $form_state['values'];
  if (!in_array($values['field_unit'][LANGUAGE_NONE][0]['value'], array('kilogram', 'pound'))) {
    return;
  }
  $field_name = $element[LANGUAGE_NONE]['#field_name'];

  if (empty($values[$field_name][LANGUAGE_NONE][0]['value'])) {
    form_error($element, t('@name is required.', array('@name' => $element[LANGUAGE_NONE]['#title'])));
  }
}
