<?php
/**
 * @file
 * Code for the Opengizra Task feature.
 */

include_once 'opengizra_task.features.inc';


/**
 * Implements hook_node_presave().
 *
 * Populate the Season reference field based on the selected entity.
 */
function opengizra_task_node_presave($node) {
  if ($node->type != 'task') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  $nids = array_keys(opengizra_general_get_node_hierarchy($node));
  $wrapper->field_reference_hierarchy->set($nids);
}

/**
 * Implements hook_comment_insert().
 *
 * Save the node task fields according to the saved comment.
 */
function opengizra_task_comment_insert($comment) {
  $wrapper = entity_metadata_wrapper('comment', $comment);
  $node = $wrapper->node->value();

  if (!$field_names = opengizra_task_intersect_fields($comment, $node)) {
    return;
  }

  $save = FALSE;
  foreach ($field_names as $field_name) {
    $value = $wrapper->{$field_name}->value();
    if ($wrapper->node->{$field_name}->value() != $value) {
      $save = TRUE;
      $wrapper->node->{$field_name}->set($value);
    }
  }

  if ($save) {
    $wrapper->node->save();
  }
}

/**
 * Return all the fields the exist in the comment and in the node.
 */
function opengizra_task_intersect_fields($comment, $node) {
  list(,, $comment_bundle) = entity_extract_ids('comment', $comment);
  $comment_fields = array_keys(field_info_instances('comment', $comment_bundle));

  list(,, $node_bundle) = entity_extract_ids('node', $node);
  $node_fields = array_keys(field_info_instances('node', $node_bundle));

  return array_intersect($comment_fields, $node_fields);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function opengizra_task_form_comment_node_task_form_alter(&$form, $form_state) {
  opengizra_task_sync_comment($form, $form_state);
}

function opengizra_task_sync_comment(&$form, $form_state) {
  $comment = $form['#entity'];
  $node = $form['#node'];
  if (!$field_names = opengizra_task_intersect_fields($comment, $node)) {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  foreach ($field_names as $field_name) {
    if (!$value = $wrapper->{$field_name}->value()) {
      continue;
    }

    if (is_object($value)) {
      $value = $wrapper->{$field_name}->value(array('identifier' => TRUE));
    }
    $form[$field_name][LANGUAGE_NONE]['#default_value'] = $value;
  }
}

