<?php
/**
 * @file
 * garmentbox_factory.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function garmentbox_factory_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function garmentbox_factory_node_info() {
  $items = array(
    'factory' => array(
      'name' => t('Factory'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'production_order' => array(
      'name' => t('Production order'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
