<?php
/**
 * @file
 * Code for the Garment-box Bubble feature.
 */

include_once 'garment_box_bubble.features.inc';

/**
 * Implements hook_view_pre_render().
 */
function garment_box_bubble_views_pre_render(&$view) {
  if (empty($view->result)) {
    garment_box_bubble_bubble_manager('view_' . $view->name . '_empty');
  }
}

/**
 * Get and set bubbles.
 */
function garment_box_bubble_bubble_manager($id = NULL) {
  $cache = &drupal_static(__FUNCTION__, array());
  if ($id) {
    // Register the ID.
    $cache[$id] = TRUE;
    return;
  }

  if (!$cache) {
    return;
  }

  $ids = array_keys($cache);

  // Get all nodes with the given IDs
  $query = new EntityFieldQuery;
  $result = $query->fieldCondition('field_bubble_id', 'value', $ids, 'IN')
    ->execute();

  if (empty($result['node'])) {
    return;
  }

  $beautytips = array();

  $nodes = node_load_multiple(array_keys($result['node']));
  foreach ($nodes as $node) {
    $wrapper = entity_metadata_wrapper('node', $node);

    $bubble_text = $wrapper->body->value->value();
    if ($wrapper->label()) {
      $bubble_text = '<h3>' . $wrapper->label() . '</h3>' . $bubble_text;
    }

    $beautytip = array(
      'cssSelect' => $wrapper->field_css_selector->value(),
      'text' => $bubble_text,
      'trigger' => 'none',
    );

    switch ($wrapper->field_display_mode->value()) {
      case 'hover':
        $beautytip['trigger'] = 'mouseover';
        break;

      case 'open':
        $beautytip['trigger'] = 'now';
        break;
    }

    $beautytips['garment_box_bubble_' . $node->nid] = $beautytip;
  }

  beautytips_add_beautytips($beautytips);
}

/**
 * Implements hook_page_build().
 */
function garment_box_bubble_page_build(&$page) {
  garment_box_bubble_bubble_manager();
}

/**
 * Implements hook_init().
 *
 * Add the generel help bubbles to pages.
 */
function garment_box_bubble_init() {
  $node_pages = array('season/%');

  $node = menu_get_object();
  if (!$node) {
    $item = menu_get_item();

    foreach ($node_pages as $node_page) {
      if (substr($item['path'], 0, strlen($node_page)) == $node_page) {
        $node = $item['map'][1]->data;
        break;
      }
    }
  }
  if (empty($node)) {
    return;
  }

  garment_box_bubble_bubble_manager($node->type . '_help');
}
