<?php
/**
 * @file
 * Code for the Opengizra Item feature.
 */

include_once 'opengizra_item.features.inc';

/**
 * Implements hook_node_presave().
 *
 * Populate the Season reference field based on the selected entity.
 */
function opengizra_item_node_presave($node) {
  if ($node->type != 'item_instance') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  $nids = array_keys(opengizra_general_get_node_hierarchy($node));
  $wrapper->field_reference_hierarchy->set($nids);
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function opengizra_item_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}
