<?php
/**
 * @file
 * Code for the Garmentbox BOL.
 */

/**
 * Get the BOL total price.
 *
 * @param $node
 *   A node holding the BOL info.
 *
 * @return
 *   The total raw price.
 */
function garmentbox_bol_get_variant_bol_price($node) {
  $wrapper = entity_metadata_wrapper('node', $node);
  // Iterate the BOL and some the prices.
  $price = 0;
  foreach ($wrapper->field_bol_info as $item_wrapper) {
    $temp_price = $item_wrapper->field_price->value();
    $price += $temp_price['amount'];
  }

  return $price;
}

/**
 * Implement hook_field_formatter_info().
 */
function garmentbox_bol_field_formatter_info() {
  return array(
    'garmentbox_bol_table' => array(
      'label' => t('BOL table'),
      'field types' => array('field_collection'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function garmentbox_bol_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $settings = $display['settings'];

  switch ($display['type']) {
    case 'garmentbox_bol_table':
      $dummy_display = $display;
      $dummy_display['type'] = 'field_collection_table_view';
      $element = field_view_field($entity_type, $entity, $field['field_name'], $dummy_display);

      // TODO: The company is set as hidden in the display settings but is still
      // shown on the header.
      // Re-set the keyes.
      $element[0]['#header'] = array_values($element[0]['#header']);

      // TODO: Add the BOL total price here.
      return $element;
  }
}