<?php
/**
 * @file
 * Code for the Opengizra season feature.
 */

include_once 'opengizra_season.features.inc';

/**
 * Implements hook_flag().
 *
 * Trim "Active Season" flag, so there's only a single flagged
 * content.
 */
function opengizra_season_flag($action, $flag, $content_id, $account) {
  if ($flag->name != 'active_season' || $action != 'flag') {
    return;
  }

  flag_trim_flag($flag, $account, 1);
}

/**
 * Implements hook_init().
 *
 * Redriect user to the active season.
 */
function opengizra_season_init() {
  if (!drupal_is_cli() && drupal_is_front_page() && $flaggings = flag_get_flagged_content('active_season')) {
    drupal_goto('node/' . $flaggings[0]->content_id);
  }
}
