<?php
// $Id: ninesixty_sub_threecol_stacked.inc,v 1.1 2010/04/11 08:42:36 amitaibu Exp $

// Plugin definition
$plugin = array(
  'title' => t('Grid 17-7'),
  'icon' => 'grid_17_7.png',
  'category' => t('Columns: 2'),
  'theme' => 'grid_17_7',
  'css' => 'grid_17_7.css',
  'regions' => array(
    'top' => t('Top'),
    'first' => t('First'),
    'last' => t('Last'),
    'bottom' => t('Bottom'),
  ),
);
